var i; 

var arLinks = new Array();

arLinks[0] = "index";
arLinks[1] = "neverending_dream";
arLinks[2] = "in_m_yhead";
arLinks[3] = "getout";
arLinks[4] = "lost_in_my_mind";
arLinks[5] = "misleading";
arLinks[6] = "underground";
arLinks[7] = "cant_swim";
arLinks[8] = "wool";
arLinks[9] = "fantasy";
arLinks[10] = "vice";
arLinks[11] = "mister";
arLinks[12] = "breathe";
arLinks[13] = "blood";
arLinks[14] = "asleep";
arLinks[15] = "down";
arLinks[16] = "lost_forever"
arLinks[17] = "occasions"
arLinks[18] = "fakeworld"
arLinks[19] = "blue_flame"
arLinks[20] = "imagine"
arLinks[21] = "hold_on"
arLinks[22] = "again"
arLinks[23] = "oooooo"
arLinks[24] = "faking"
arLinks[25] = "try"
arLinks[26] = "destroy"
arLinks[27] = "say_goodbye"
arLinks[28] = "anotherone"
arLinks[29] = "help"
arLinks[30] = "head"
arLinks[31] = "mute"
arLinks[32] = "years"
arLinks[33] = "without"
arLinks[34] = "equa"
arLinks[35] = "me_and_john"
arLinks[36] = "flesh"
arLinks[37] = "go_back"
arLinks[38] = "enter"
arLinks[39] = "notbreathe"
arLinks[40] = "diarys"
arLinks[41] = "gone"
arLinks[42] = "excursion"
arLinks[42] = "https://www.youtube.com/@silentdork"

i = Math.floor( Math.random() * arLinks.length );
window.location = arLinks[i];
